[build]
  publish = "."
  command = ""
  environment = { NODE_VERSION = "16", NPM_FLAGS = "--no-optional" }

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for all responses
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://player.vimeo.com https://*.vimeocdn.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://i.vimeocdn.com https://image.tmdb.org; font-src 'self' https://fonts.gstatic.com; frame-src 'self' https://player.vimeo.com; frame-ancestors 'self' https://player.vimeo.com; connect-src 'self' https://api.vimeo.com; media-src 'self' https://player.vimeo.com;"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Feature-Policy = "fullscreen 'self' https://player.vimeo.com"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000, immutable"
    
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com https://kit.fontawesome.com https://cdn.auth0.com;
      style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com;
      img-src 'self' data: https: http:;
      font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com data:;
      connect-src 'self' https://*.tmdb.org https://api.themoviedb.org https://*.auth0.com https://dev-jphdcibt0uw3a4jt.us.auth0.com https://cdn.auth0.com;
      frame-src 'self' https://www.youtube.com https://cdn.auth0.com https://dev-jphdcibt0uw3a4jt.us.auth0.com;
      media-src 'self' https:;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://dev-jphdcibt0uw3a4jt.us.auth0.com;
      frame-ancestors 'self';
      block-all-mixed-content;
      upgrade-insecure-requests;
    """
    
    # HSTS (only enable in production)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# HTML files should not be cached by the browser
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Service worker
[[headers]]
  for = "/sw-new.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

# Manifest file
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/manifest+json; charset=utf-8"

# Icons and assets
[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
